name: Upload Python Package to PyPi


on:
  push:
    branches:
      - master # or a pattern like "*" for including all branches
    paths:
      - balatromobile/__version__.py

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypitest
      url: https://pypi.org/p/balatromobile
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Build package
      run: |
        flit build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
